version: '3.8'
services:
  postgres:
    image: postgres:alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=koala
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=koala@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 4040:80
    depends_on:
      - postgres